### ISSUE TITLE
Add 버튼 위치 및 스타일링

### ISSUE THREAD

**Issue by azxca1731** [azxca1731/react-calenpicker#102]
**Is your feature request related to a problem? Please describe.**
현재 Add 버튼의 위치가 헤드에 있는데 위치를 캘린더 하단부로 옮기려 한다.

**Describe the solution you'd like**
현재 너무 못생기고 위치가 좀 밑이 더 좋아보인다

**Comment by rhdtl78** [comment]
- [ ] 버튼 위치 변경
