### ISSUE TITLE
엔자임 테스트 추가

### ISSUE THREAD

**Issue by azxca1731** [azxca1731/react-calenpicker#2]
현재 테스트는 단순히 렌더링이 문제없나 있나만 보는 수준이라 테스트가 더 필요하다

**Comment by rhdtl78** [comment]
1. 특정 props 에 따라 컴포넌트가 크래쉬 없이 잘 렌더링이 되는지 확인
2. 이전에 렌더링했던 결과와, 지금 렌더링한 결과가 일치하는지 확인
3. 특정 DOM 이벤트를 시뮬레이트 하여, 원하는 변화가 제대로 발생하는지 확인
4. 렌더링된 결과물을 이미지 로 저장을 하여 픽셀을 하나하나 확인해서 모두 일치하는지 확인

**Comment by rhdtl78** [comment]
Story1. 사용자는 CssProvider를 사용할 수 있다. 
- Scenario1
given: 설정 없이
when: CssProvider를 사용하면
then: 기본값을 가진 props를 제공한다. 

- Scenario2.
given: sizeOption 에 "sm"을 입력하고
when: cssProvider를 사용하면
then: "sm"에 해당하는 크기 객체를 얻는다.

**Comment by rhdtl78** [comment]
Story2. 사용자는 CssProvider를 통해 크기를 조절할 수 있다.

- Senario 1.
  - given: 세부 크기를 객체형태로 sizeOption에 입력하고
  - when: CssProvider를 사용하면
  - then: 해당 옵션이 반영되어있는 CssProvider를 얻는다.

**Comment by rhdtl78** [comment]
DateProvider
Story1. 사용자는 DateProvider를 사용할 수 있다.
Story2. 사용자는 DateProvider를 한 달에 관련한 정보들을 관리할 수 있다.
Story3. 사용자는 DateProvider를 통해 클릭에 관한 행동을 관리할 수 있다.

**Comment by rhdtl78** [comment]
Story1. 사용자는 DateProvider를 사용할 수 있다.
- Senario 1.
  - given: 설정 없이
  - when: DateProvider를 사용하면
  - then: 에러가 발생한다.
