### ISSUE TITLE
일정 삭제

### ISSUE THREAD

**Issue by rhdtl78** [azxca1731/react-calenpicker#78]
**Is your feature request related to a problem? Please describe.**
 설계에 구멍이 있었다. 일정 생성은 가능하나 일정 취소(삭제)가 불가능하다.
**Describe the solution you'd like**
 따라서 일정을 삭제할 버튼을 추가한다. 일정 편집 모달에 해당 일정 정보를 불러오고, 삭제할 수 있는 버튼을 노출한다.

**Comment by azxca1731** [comment]
삭제 버튼을 캘린더에 따로 만들지 말고 모달에 만드는게 좋을듯!

**Comment by rhdtl78** [comment]
> 정 편집 모달에 해당 일정 정보를 불러오고, 삭제할 수 있는 버튼을 노출한다.
