### ISSUE TITLE
연속적인 일정 같이 묶어 주기

### ISSUE THREAD

**Issue by azxca1731** [azxca1731/react-calenpicker#82]
**Is your feature request related to a problem? Please describe.**
현재는 연속적인 일정을 보여줄 방법이 없다

**Describe the solution you'd like**
연속적인 일정일 경우 하나의 바처럼 묶어서 보여주면 좋을것 같다

**Comment by rhdtl78** [comment]
일정 내용으로 packing하려 했으나 동일한 내용(text)로 다른 일정인 경우가 존재할 수 있음.
따라서 일정에 따라 고유한 id를 부여, 일정을 입력하는 방법을 변경해야 할듯.

**Comment by rhdtl78** [comment]
ScheduleProvider를 만들어 관리하게 함이 용이해 보임.
